name: "Build and Push PHP-FPM 8.3 Docker Image"

on:
  push:
    branches: [ "main" ]
    paths:
      - 'php-fpm-83/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: sustartx/php-fpm-83
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Login
        env:
          DOCKER_REPOSITORY_HOST: ${{ vars.REPOSITORY_HOST }}
          DOCKER_REPOSITORY_USER: ${{ vars.REPOSITORY_USER }}
          DOCKER_REPOSITORY_PASS: ${{ secrets.REPOSITORY_PASSWORD }}
        run: |
          echo "$DOCKER_REPOSITORY_PASS" | docker login --username "$DOCKER_REPOSITORY_USER" --password-stdin $DOCKER_REPOSITORY_HOST

      - name: Build the Docker Image
        env:
          DOCKER_REPOSITORY_HOST: ${{ vars.REPOSITORY_HOST }}
        run: |
          cd php-fpm-83
          docker build . \
            -t $DOCKER_REPOSITORY_HOST/${{ env.IMAGE_NAME }}:latest

      - name: Push the Docker Image
        env:
          DOCKER_REPOSITORY_HOST: ${{ vars.REPOSITORY_HOST }}
          DOCKER_REPOSITORY_USER: ${{ vars.REPOSITORY_USER }}
          DOCKER_REPOSITORY_PASS: ${{ secrets.REPOSITORY_PASSWORD }}
        run: |
          echo "$DOCKER_REPOSITORY_PASS" | docker login --username "$DOCKER_REPOSITORY_USER" --password-stdin $DOCKER_REPOSITORY_HOST
          docker push $DOCKER_REPOSITORY_HOST/${{ env.IMAGE_NAME }}:latest
